export const patientSeed = [
  {
    "firstName": "Alice",
    "lastName": "Johnson",
    "dateOfBirth": "1975-04-23",
    "gender": "F",
    "contactNumber": "+12345678901",
    "email": "alice.johnson@example.com",
    "address": "123 Cherry Lane, Springfield, SP",
    "medicalHistory": "No known allergies. Previous surgery for appendicitis.",
    "bloodType": "A+",
    "allergies": "None",
    "medications": "Ibuprofen as needed",
    "surgeries": "Appendectomy",
    "chronicConditions": "Hypertension",
    "lastVisitDate": "2023-03-15",
    "nextAppointmentDate": "2023-09-10"
  },
  {
    "firstName": "Bob",
    "lastName": "Smith",
    "dateOfBirth": "1988-12-10",
    "gender": "M",
    "contactNumber": "+19876543210",
    "email": "bob.smith@example.com",
    "address": "456 Oak Street, Rivertown, RT",
    "medicalHistory": "Asthmatic, controlled with medication.",
    "bloodType": "O-",
    "allergies": "Penicillin",
    "medications": "Albuterol, Loratadine",
    "surgeries": "Tonsillectomy",
    "chronicConditions": "Asthma",
    "lastVisitDate": "2023-04-20",
    "nextAppointmentDate": "2023-10-25"
  },
  {
    "firstName": "Charlie",
    "lastName": "Brown",
    "dateOfBirth": "1995-08-05",
    "gender": "M",
    "contactNumber": "+16504321876",
    "email": "charlie.brown@example.com",
    "address": "789 Maple Avenue, Greenvale, GV",
    "medicalHistory": "No known allergies.",
    "bloodType": "B+",
    "allergies": "None",
    "medications": "None",
    "surgeries": "None",
    "chronicConditions": "None",
    "lastVisitDate": "2023-02-10",
    "nextAppointmentDate": "2023-08-15"
  },
  {
    "firstName": "Diana",
    "lastName": "Miller",
    "dateOfBirth": "1982-03-18",
    "gender": "F",
    "contactNumber": "+12098765432",
    "email": "diana.miller@example.com",
    "address": "987 Pine Street, Hilltop, HT",
    "medicalHistory": "Allergic to seafood. Knee surgery in 2010.",
    "bloodType": "AB-",
    "allergies": "Seafood",
    "medications": "Pain relievers as needed",
    "surgeries": "Knee surgery",
    "chronicConditions": "None",
    "lastVisitDate": "2023-06-05",
    "nextAppointmentDate": "2023-12-20"
  },
  {
    "firstName": "Eleanor",
    "lastName": "Clark",
    "dateOfBirth": "1990-11-30",
    "gender": "F",
    "contactNumber": "+15551234567",
    "email": "eleanor.clark@example.com",
    "address": "234 Elm Lane, Woodville, WV",
    "medicalHistory": "No known allergies. Recent flu vaccination.",
    "bloodType": "O+",
    "allergies": "None",
    "medications": "Vitamin supplements",
    "surgeries": "None",
    "chronicConditions": "None",
    "lastVisitDate": "2023-01-25",
    "nextAppointmentDate": "2023-07-30"
  },
  {
    "firstName": "Frank",
    "lastName": "Taylor",
    "dateOfBirth": "1986-07-12",
    "gender": "M",
    "contactNumber": "+16667778888",
    "email": "frank.taylor@example.com",
    "address": "345 Cedar Road, Lakeside, LS",
    "medicalHistory": "No known allergies. Annual checkups.",
    "bloodType": "A-",
    "allergies": "None",
    "medications": "Multivitamins",
    "surgeries": "None",
    "chronicConditions": "None",
    "lastVisitDate": "2023-05-12",
    "nextAppointmentDate": "2023-11-17"
  },
  {
    "firstName": "Grace",
    "lastName": "Anderson",
    "dateOfBirth": "1978-09-14",
    "gender": "F",
    "contactNumber": "+14443332222",
    "email": "grace.anderson@example.com",
    "address": "567 Walnut Street, Hillcrest, HC",
    "medicalHistory": "No known allergies. Occasional migraines.",
    "bloodType": "B-",
    "allergies": "None",
    "medications": "Migraine medication",
    "surgeries": "None",
    "chronicConditions": "Migraines",
    "lastVisitDate": "2023-07-18",
    "nextAppointmentDate": "2024-01-22"
  },
  {
    "firstName": "Harry",
    "lastName": "White",
    "dateOfBirth": "1993-02-28",
    "gender": "M",
    "contactNumber": "+18889997777",
    "email": "harry.white@example.com",
    "address": "678 Pine Lane, Hillside, HS",
    "medicalHistory": "No known allergies. Routine blood tests.",
    "bloodType": "AB+",
    "allergies": "None",
    "medications": "None",
    "surgeries": "None",
    "chronicConditions": "None",
    "lastVisitDate": "2023-08-30",
    "nextAppointmentDate": "2024-02-04"
  },
  {
    "firstName": "Isabel",
    "lastName": "Turner",
    "dateOfBirth": "1980-05-17",
    "gender": "F",
    "contactNumber": "+17776665555",
    "email": "isabel.turner@example.com",
    "address": "789 Oak Avenue, Riverside, RS",
    "medicalHistory": "Allergic to cats. Annual checkups.",
    "bloodType": "O-",
    "allergies": "Cats",
    "medications": "None",
    "surgeries": "None",
    "chronicConditions": "None",
    "lastVisitDate": "2023-09-25",
    "nextAppointmentDate": "2024-03-10"
  },
  {
    "firstName": "Jack",
    "lastName": "Harrison",
    "dateOfBirth": "1997-06-08",
    "gender": "M",
    "contactNumber": "+16669998888",
    "email": "jack.harrison@example.com",
    "address": "890 Maple Road, Maplewood, MW",
    "medicalHistory": "No known allergies. Sports injuries treated.",
    "bloodType": "A-",
    "allergies": "None",
    "medications": "Pain relievers",
    "surgeries": "Sports injuries",
    "chronicConditions": "None",
    "lastVisitDate": "2023-10-10",
    "nextAppointmentDate": "2024-04-15"
  }
];
